### ISSUE TITLE
目前还是不清楚发送单个视频请求的参数

### ISSUE THREAD

**Issue by wakasann** [wakasann/ksusegradlegetsinglev#1]
目前知道一些参数是固定死的，单不清楚 retrofit 是可以把一些参数，可以带到目前这个定义的请求中的

`com.yxcorp.gifshow.retrofit.service.KwaiApiService` Line 1220

定义

```
@o(a = "n/tokenShare/info/byText")
    @e
    l<a<TokenInfoModel>> tokenShareInfo(@c(a = "shareText") String str);
```

调用 `com.yxcorp.gifshow.init.module.KwaiTokenInitModule` line 44

```
return KwaiApp.getApiService().tokenShareInfo(str).map(KwaiTokenInitModule$1$$Lambda$1.a).map(((LoginPlugin) b.a(LoginPlugin.class)).newTokenFunctionConvertTokenInfoModel());

```

感觉这个方法就一个参数，不清楚是怎么把Map.put里面的属性也带上的呢❓

**Comment by junshenshi** [comment]
伙计 看看这个签名https://blog.csdn.net/u010814849/article/details/88207931

**Comment by wakasann** [comment]
> 伙计 看看这个签名https://blog.csdn.net/u010814849/article/details/88207931

感谢，这个博主真厉害

**Comment by junshenshi** [comment]
> > 伙计 看看这个签名https://blog.csdn.net/u010814849/article/details/88207931
> 
> 感谢，这个博主真厉害

伙计能加个wx不？wx:zouyejunjun

**Comment by TeslaLyon** [comment]
hello，请教一下，如何生成sig参数？想获取用户所有作品

**Comment by wakasann** [comment]
> hello，请教一下，如何生成sig参数？想获取用户所有作品

抱歉，目前我不清楚如何生成sig参数，帮不上忙

**Comment by wakasann** [comment]
下载快手无水印视频我个人使用 [使用 fiddler 和PHP程序将快手App中喜欢的短视频保存在电脑上](https://www.cnblogs.com/fsong/p/12305985.html) 的方法了，没有心力去研究反编译后快手apk的一些代码。
